dataset: data.json

plots:
  - name: Spot pris (NOK/MWh)
    type: timeseries
    x: dato_Id
    y: Price
    series:
      - query: src == 'nordpool' & omrnr == 1
        name: NO1
      - query: src == 'nordpool' & omrnr == 2
        name: NO2
      - query: src == 'nordpool' & omrnr == 3
        name: NO3
      - query: src == 'nordpool' & omrnr == 4
        name: NO4
      - query: src == 'nordpool' & omrnr == 5
        name: NO5

  - name: Fyllingsgrad
    type: timeseries
    x: dato_Id
    y: fyllingsgrad
    series:
      - query: src == 'NVE' & omrnr == 1 & omrType == 'EL'
        name: NO1
      - query: src == 'NVE' & omrnr == 2 & omrType == 'EL'
        name: NO2
      - query: src == 'NVE' & omrnr == 3 & omrType == 'EL'
        name: NO3
      - query: src == 'NVE' & omrnr == 4 & omrType == 'EL'
        name: NO4
      - query: src == 'NVE' & omrnr == 5 & omrType == 'EL'
        name: NO5

  - name: Endring i fyllingsgrad vs. pris (totalt)
    type: parametric
    x:
      query: src == 'NVE' & omrType == 'EL'
      field: endring_fyllingsgrad
    y: 
      query: src == 'nordpool'
      field: Price

  - name: Endring i fyllingsgrad vs. pris NO1
    type: parametric
    x:
      query: src == 'NVE' & omrType == 'EL' & omrnr == 1
      field: endring_fyllingsgrad
    y: 
      query: src == 'nordpool' & omrnr == 1
      field: Price
