language: python

install:
    - pip install .
    - pip install flake8
    - pip install pytest

script:
    - python --version
    - flake8 smv/
    - flake8 app/
    - bash run_cli.sh
    - pytest tests/ -m "not slow"