language: python

python:
    - "3.8"

install:
    - pip install .
    - pip install flake8
    - pip install pytest

script:
    - python --version
    - flake8 smv/
    - flake8 app/
    - flake8 tests/
    - bash run_cli.sh
    - pytest tests/